package main

const PROCESS_START = "MINERBINSTART"
const PROCESS_END = "MINERBINSTOP"

const HASH_TEST_START = "HASHTEST_START"
const HASH_TEST_STOP = "HASHTEST_STOP"

const MINER_TEST_START = "MINERTEST_START"
const MINER_TEST_STOP = "MINERTEST_STOP"

const MINER_START = "MINER_START"
const MINER_STOP = "MINER_STOP"

const EXIT_COMMAND = "EXIT"
const MINE_COMMAND = "MINE"
const UPDATE_BLOCK = "CHANGEBLOCK"
const UPDATE_TARGET = "CHANGETARGET"
const UPDATE_ADDRESS = "CHANGEADDRESS"
const SPEED_REPORT = "SPEEDREPORT"
const TEST_NOSOHASH_COMMAND = "TESTHASH"
const TEST_NETWORK_COMMAND = "TESTNET"
const TEST_HASH_COMMAND = "TESTHASH"
const TEST_MINER_COMMAND = "TESTMINER"
